# Generated by Django 4.0.3 on 2022-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='old_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='price_difference',
            field=models.FloatField(default=0),
        ),
    ]
